### ISSUE TITLE
Apple app store rejects apps due to react-native-location-switch

### ISSUE THREAD

**Issue by webraptor** [philiWeitz/react-native-location-switch#9]
The library uses App-Prefs:root= which in turn triggers rejection during new store submission reviews.

```
From Apple
2. 5 Performance: Software Requirements
Guideline 2.5.1 - Performance - Software Requirements

Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.
```

**Culprit** 
```
ios/RNReactNativeLocationSwitch.m:23 [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"App-Prefs:root=Privacy&path=LOCATION"] options:@{}
```

Any ideas if this could be easily fixed?

**Comment by trungkhtn** [comment]
same problem, please help us.

**Comment by webraptor** [comment]
We replied to Apple describing how and why we use the package and they validated the submission. We've had subsequent releases since then without the problem being mentioned again, so its likely you'll only have to do it once.

**Comment by nadagamal** [comment]
Same problem, guys did anyone solve this issue?
Thanks

**Comment by webraptor** [comment]
@nadagamal if you read my last comment https://github.com/philiWeitz/react-native-location-switch/issues/9#issuecomment-404521817, just before yours, you'll see the solution.

I guess that if you can't make a case for why you use the feature so that Apple approves it, you shouldn't be using the feature all together.

**Comment by ranjit-nyros** [comment]
@webraptor . I am getting the same issue as above. The app got rejected from Apple.
How to fix it, or tell me the steps where to give the details of settings usage.so that i will give the details in it and submit the app to store.

**Comment by webraptor** [comment]
@ranjit-nyros Unfortunately I cannot help you. You're the only ones who know how and why you use the feature. The only way is to talk to Apple store review technicians and let them know exactly why your app needs the feature and it may be approved if the use case are all right and provide a valuable functionality to the user.

**Comment by Hoihhv** [comment]
> same problem, please help us.

same problem, please help us.

**Comment by TxusBlack** [comment]
It didn't work for me, my solution was to show an alert to indicate to the user that he must activate the GPS position and open the configuration. Also, Apple rejected our application always.

**Comment by Amenulhaq** [comment]
I am also facing this issue this is what apple said

> Your app uses or references the following non-public APIs:
app-prefs:root=privacy&path=location
The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

**Comment by imrankhanmemon** [comment]
I am also facing same issue,

Your app uses or references the following non-public APIs:
app-prefs:root=privacy&path=location
The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

 i have used react-native-location-switch plugin in which URL scheme is 
app-prefs:root=privacy&path=location.
My app help user to find near by restaurant by providing its location manually or by pressing locate me functionality where i need device location On.
